# Generated by Django 3.0 on 2020-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picm',
            old_name='id',
            new_name='idd',
        ),
        migrations.AddField(
            model_name='picm',
            name='name',
            field=models.CharField(default=44, max_length=100),
            preserve_default=False,
        ),
    ]
