# Generated by Django 3.0 on 2020-05-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200501_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picm',
            name='pic',
            field=models.CharField(max_length=100),
        ),
    ]
